### PR TITLE
WIP for Meteor integration

### PR DESCRIPTION
**Pull request by chip**
@someatoms - Since I'm new to this process, this might take a few iterations before it will be ready. I'd suggest having @splendido take a look and give the thumbs up before merging.

There are a few `TODO`'s that we'll need to fill in as well.

@splendido - I used a sample `package.js` and `package.json` that @dandv created for the FontAwesome project, so hopefully that will be a good starting point for this package. Please LMK your thoughts and if there's an easy way for me to test this integration.

Thanks!

### CODE REVIEW

**Comment by chip** [comment]
This PR is for #19.

**Comment by splendido** [comment]
Hi @chip and @someatoms,

From what I can see, the only thing we have to sort out is how to keep version numbers inside `package.json`, `bower.json` and `package.js` in sync.
This somehow depends on the *build* process @someatoms uses to create new releases.
Since there's no tarce of an automated build process, I guess the version number was bumped manually so far.

Would it be fine to have to bump them manually also in the future?
Would this be error prone?

**Comment by someatoms** [comment]
I have used git tags for versions as bower [doesn't actually use](https://github.com/bower/bower.json-spec#version) the `version` property right now as far as I understand. Or is the bower `version` property required in some way?

With the `package.js` implementation in this PR the only place the version is required to be manually entered is in the packages.json which is fine for me. I will probably just create a git hook which automatically updates it (could also be done for bower I suppose).

**Comment by chip** [comment]
@someatoms - I only put the `version` in bower.json because I saw it used in another example for Meteor Packaging. Upon a second review, I see that I should've put that in the package.json file instead of bower.json. If that sounds reasonable, what version would you prefer?

**Comment by someatoms** [comment]
Sounds good! The current version of the plugin is `1.2.3`.

**Comment by chip** [comment]
Great!  I just pushed up those revisions.

Also, please see the TODO in package.js:
```
// TODO This package need to be published on npmjs.org
```

It will only be used as a fallback, so there's probably no rush, but thought you should know.

**Comment by splendido** [comment]
Hey guys,
if the version bumping is not a problem (and maybe could be automatized), I'd prefer to keep the `package.js` as lean as the following:

```javascript
// Package metadata file for Meteor.js.
'use strict';

Package.describe({
  name: 'jspdf:autotable',  // http://atmospherejs.com/jspdf/autotable
  summary: 'PDF table generator in javascript (jspdf plugin)',
  version: '1.2.3',
  git: 'https://github.com/someatoms/jsPDF-AutoTable.git',
  documentation: 'README.md'
});

Package.onUse(function (api) {
  api.imply('jspdf:jspdf');
  api.addFiles('jsPDF-AutoTable/jspdf.plugin.autotable.js', 'client');
});
```

@chip: we should finish the publish for `jspfd:jspdf` first which needs to be implied by this package...


In any case, I'd also like to package to be kept up to date with [autopublish.meteor.com](http://autopublish.meteor.com/) not to ask @someatoms to manually publish for meteor on his own.

See [the PR we had for bootstrap](https://github.com/twbs/bootstrap/pull/15716) with some more details about how it works.

**Comment by someatoms** [comment]
Just found out that `jspdf` does not work with node so I won't publish this library on npm either. With that and autopublish in mind the `package.js` splendido posted seems to be everything needed for official meteor support?

**Comment by chip** [comment]
@someatoms - Thanks for the info on `jspdf`. Earlier this week @splendido and I [completed the Meteor integration for jspdf:core](https://github.com/MeteorPackaging/jspdf-core-wrapper). I still need to test it locally, but once that is done I'll use that as a boilerplate for your package. If you have time, feel free to check it out.

**Comment by chip** [comment]
@splendido - I think the issue is that https://github.com/MeteorPackaging/jspdf-autotable is a fork of the this repo, but we've recently decided to approach this in a different manner. I think the MeteorPackaging repo just needs to be a blank slate instead of a fork. Then I can issue my PR against that and we can merge it in there instead of here. 

Once that is done, we can have @someatoms sign up at autopublish and test.

Your thoughts?

**Comment by chip** [comment]
In case it's not clear, my previous comment is in regards to this PR: https://github.com/someatoms/jsPDF-AutoTable/pull/31.

**Comment by splendido** [comment]
I've just created [jspdf-AutoTable-wrapper](https://github.com/MeteorPackaging/jspdf-AutoTable-wrapper).
This way the only thing we'll need from @someatoms will be a webhook to les us know about new releases and this repo could remain clean without additional files for Meteor only cluttering it.

**Comment by someatoms** [comment]
Cool! Webhook to where?

**Comment by chip** [comment]
@someatoms - Check this out - https://autopublish.meteor.com/howitworks. There's a brief video and a few steps to read through there. Basically, once this webhook is setup it will autopublish your changes to [Atmosphere](http://atmospherejs.com).

**Comment by someatoms** [comment]
So a webhook for this repo should go to `https://autopublish.meteor.com/publish` as shown in the video?

**Comment by splendido** [comment]
Hey @someatoms, sorry for the fragmented info!

Yes the video is for enabling repositories containing Meteor packages.
This time we're following a bit different direction though...

Coould you please set up a webhook for us looking at [this example](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/How-to-manually-set-up-web-hooks#releases)?
And yes, the address should now be `https://autopublish.meteor.com/publish` with `https' and not `http`.

Thanks a bunch!

**Comment by splendido** [comment]
Wow, that was quick!

Webhook received :-)

**Comment by someatoms** [comment]
Sweet! I get a warning, but if it works its all good I suppose. screenshot_2015-05-17-11-03-40

**Comment by splendido** [comment]
mmm, weird!
Could you please have a look among the details of the failed delivery and check the `response` tab?
It might be I'm sending out an invalid response, but at least the hook arrived...

**Comment by splendido** [comment]
No more need to check!
It should have got "No subscription found for this repository!" as reply error, but that's somehow correct since manual hook creation for non-meteor package repos is still not *supported*.

But the hook is there and we have its details in the DB now! :-)

I'd say this concludes this *integration* process.

Thanks again for your availability and collaboration!!!

**Comment by someatoms** [comment]
I know many people who are using meteor, but have not had the opportunity myself to check it out in any bigger project yet. So it's great that you guys made this happen! Thanks!

**Comment by splendido** [comment]
@someatoms, I've just noticed you've used *tags* and not *releases* for your latest versions...
...could you please update the webhook to reflect [these settings](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/How-to-manually-set-up-web-hooks#tags): basically we'd like to be informed when you create a new tag ;-)

...as the very last request: would it be too much asking you to keep also a `version` field inside the `bower.json` file like MrRio is doing for jsPDF [here](https://github.com/MrRio/jsPDF/blob/master/bower.json#L3)? This way we're going to be able to read it directly from the `bower.json` file instead of using the tag name...

Thanks again,
Luca

**Comment by someatoms** [comment]
Before the webhook was triggered only when new tags were created. So it should already have been correct right?  Anyway I updated the webhook to trigger when new releases are published as well just in case I do that in the future. Version number in the `bower.json` file is probably a good idea. Will probably do that in the next version. All good!

**Pull request closed without merging**
